In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

In [ ]:
data=pd.read_csv(r"C:\Users\Es\Downloads\Titanic-Dataset (1).csvsam")
data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [16]:
encoder=OneHotEncoder(sparse_output=False)
one=encoder.fit_transform(data[['Embarked']].head(12))

In [17]:
one

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [18]:
data['Embarked']=data['Embarked'].astype(str)

In [19]:
feature_names = encoder.get_feature_names_out(['Embarked'])
feature_names

array(['Embarked_C', 'Embarked_Q', 'Embarked_S'], dtype=object)

In [20]:
data_encoder=pd.DataFrame(one,columns=feature_names)

In [21]:
data_encoder

    Embarked_C  Embarked_Q  Embarked_S
0          0.0         0.0         1.0
1          1.0         0.0         0.0
2          0.0         0.0         1.0
3          0.0         0.0         1.0
4          0.0         0.0         1.0
5          0.0         1.0         0.0
6          0.0         0.0         1.0
7          0.0         0.0         1.0
8          0.0         0.0         1.0
9          1.0         0.0         0.0
10         0.0         0.0         1.0
11         0.0         0.0         1.0

In [23]:
ind=data.columns.get_loc('Embarked')
ind

11

In [24]:
before = data.iloc[:, :ind]
after = data.iloc[:, ind+1:]

data_final = pd.concat([before, data_encoder, after], axis=1)
data_final.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,0.0,0.0,1.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,1.0,0.0,0.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,0.0,0.0,1.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,0.0,0.0,1.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,0.0,0.0,1.0
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,0.0,1.0,0.0
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,0.0,0.0,1.0
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,0.0,0.0,1.0
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,0.0,0.0,1.0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,1.0,0.0,0.0

In [31]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [33]:
missing_value=data.isnull().sum()
missing_value

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [35]:
missing_percent=(data.isnull().sum()/len(data))*100
missing_percent

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [37]:
imp=SimpleImputer(strategy="mean")

data_imputed=imp.fit_transform(data[['Age']])

print(data_imputed)

[[22.        ]
 [38.        ]
 [26.        ]
 [35.        ]
 [35.        ]
 [29.69911765]
 [54.        ]
 [ 2.        ]
 [27.        ]
 [14.        ]
 [ 4.        ]
 [58.        ]
 [20.        ]
 [39.        ]
 [14.        ]
 [55.        ]
 [ 2.        ]
 [29.69911765]
 [31.        ]
 [29.69911765]
 [35.        ]
 [34.        ]
 [15.        ]
 [28.        ]
 [ 8.        ]
 [38.        ]
 [29.69911765]
 [19.        ]
 [29.69911765]
 [29.69911765]
 [40.        ]
 [29.69911765]
 [29.69911765]
 [66.        ]
 [28.        ]
 [42.        ]
 [29.69911765]
 [21.        ]
 [18.        ]
 [14.        ]
 [40.        ]
 [27.        ]
 [29.69911765]
 [ 3.        ]
 [19.        ]
 [29.69911765]
 [29.69911765]
 [29.69911765]
 [29.69911765]
 [18.        ]
 [ 7.        ]
 [21.        ]
 [49.        ]
 [29.        ]
 [65.        ]
 [29.69911765]
 [21.        ]
 [28.5       ]
 [ 5.        ]
 [11.        ]
 [22.        ]
 [38.        ]
 [45.        ]
 [ 4.        ]
 [29.69911765]
 [29.69911765]
 [29.        ]
 [19.        ]
 [17.        ]
 [26.        ]
 [32.        ]
 [16.        ]
 [21.        ]
 [26.        ]
 [32.        ]
 [25.        ]
 [29.69911765]
 [29.69911765]
 [ 0.83      ]
 [30.        ]
 [22.        ]
 [29.        ]
 [29.69911765]
 [28.        ]
 [17.        ]
 [33.        ]
 [16.        ]
 [29.69911765]
 [23.        ]
 [24.        ]
 [29.        ]
 [20.        ]
 [46.        ]
 [26.        ]
 [59.        ]
 [29.69911765]
 [71.        ]
 [23.        ]
 [34.        ]
 [34.        ]
 [28.        ]
 [29.69911765]
 [21.        ]
 [33.        ]
 [37.        ]
 [28.        ]
 [21.        ]
 [29.69911765]
 [38.        ]
 [29.69911765]
 [47.        ]
 [14.5       ]
 [22.        ]
 [20.        ]
 [17.        ]
 [21.        ]
 [70.5       ]
 [29.        ]
 [24.        ]
 [ 2.        ]
 [21.        ]
 [29.69911765]
 [32.5       ]
 [32.5       ]
 [54.        ]
 [12.        ]
 [29.69911765]
 [24.        ]
 [29.69911765]
 [45.        ]
 [33.        ]
 [20.        ]
 [47.        ]
 [29.        ]
 [25.        ]
 [23.        ]
 [19.        ]
 [37.        ]
 [16.        ]
 [24.        ]
 [29.69911765]
 [22.        ]
 [24.        ]
 [19.        ]
 [18.        ]
 [19.        ]
 [27.        ]
 [ 9.        ]
 [36.5       ]
 [42.        ]
 [51.        ]
 [22.        ]
 [55.5       ]
 [40.5       ]
 [29.69911765]
 [51.        ]
 [16.        ]
 [30.        ]
 [29.69911765]
 [29.69911765]
 [44.        ]
 [40.        ]
 [26.        ]
 [17.        ]
 [ 1.        ]
 [ 9.        ]
 [29.69911765]
 [45.        ]
 [29.69911765]
 [28.        ]
 [61.        ]
 [ 4.        ]
 [ 1.        ]
 [21.        ]
 [56.        ]
 [18.        ]
 [29.69911765]
 [50.        ]
 [30.        ]
 [36.        ]
 [29.69911765]
 [29.69911765]
 [ 9.        ]
 [ 1.        ]
 [ 4.        ]
 [29.69911765]
 [29.69911765]
 [45.        ]
 [40.        ]
 [36.        ]
 [32.        ]
 [19.        ]
 [19.        ]
 [ 3.        ]
 [44.        ]
 [58.        ]
 [29.69911765]
 [42.        ]
 [29.69911765]
 [24.        ]
 [28.        ]
 [29.69911765]
 [34.        ]
 [45.5       ]
 [18.        ]
 [ 2.        ]
 [32.        ]
 [26.        ]
 [16.        ]
 [40.        ]
 [24.        ]
 [35.        ]
 [22.        ]
 [30.        ]
 [29.69911765]
 [31.        ]
 [27.        ]
 [42.        ]
 [32.        ]
 [30.        ]
 [16.        ]
 [27.        ]
 [51.        ]
 [29.69911765]
 [38.        ]
 [22.        ]
 [19.        ]
 [20.5       ]
 [18.        ]
 [29.69911765]
 [35.        ]
 [29.        ]
 [59.        ]
 [ 5.        ]
 [24.        ]
 [29.69911765]
 [44.        ]
 [ 8.        ]
 [19.        ]
 [33.        ]
 [29.69911765]
 [29.69911765]
 [29.        ]
 [22.        ]
 [30.        ]
 [44.        ]
 [25.        ]
 [24.        ]
 [37.        ]
 [54.        ]
 [29.69911765]
 [29.        ]
 [62.        ]
 [30.        ]
 [41.        ]
 [29.        ]
 [29.69911765]
 [30.        ]
 [35.        ]
 [50.        ]
 [29.69911765]
 [ 3.        ]
 [52.        ]
 [40.        ]
 [29.69911765]
 [36.        ]
 [16.        ]
 [25.        ]
 [58.        ]
 [35.        ]
 [29.69911765]
 [25.        ]
 [41.        ]
 [37.        ]
 [29.69911765]
 [63.        ]
 [45.        ]
 [29.69911765]
 [ 7.        ]
 [35.        ]
 [65.        ]
 [28.        ]
 [16.        ]
 [19.        ]
 [29.69911765]
 [33.        ]
 [30.        ]
 [22.        ]
 [42.        ]
 [22.        ]
 [26.        ]
 [19.        ]
 [36.        ]
 [24.        ]
 [24.        ]
 [29.69911765]
 [23.5       ]
 [ 2.        ]
 [29.69911765]
 [50.        ]
 [29.69911765]
 [29.69911765]
 [19.        ]
 [29.69911765]
 [29.69911765]
 [ 0.92      ]
 [29.69911765]
 [17.        ]
 [30.        ]
 [30.        ]
 [24.        ]
 [18.        ]
 [26.        ]
 [28.        ]
 [43.        ]
 [26.        ]
 [24.        ]
 [54.        ]
 [31.        ]
 [40.        ]
 [22.        ]
 [27.        ]
 [30.        ]
 [22.        ]
 [29.69911765]
 [36.        ]
 [61.        ]
 [36.        ]
 [31.        ]
 [16.        ]
 [29.69911765]
 [45.5       ]
 [38.        ]
 [16.        ]
 [29.69911765]
 [29.69911765]
 [29.        ]
 [41.        ]
 [45.        ]
 [45.        ]
 [ 2.        ]
 [24.        ]
 [28.        ]
 [25.        ]
 [36.        ]
 [24.        ]
 [40.        ]
 [29.69911765]
 [ 3.        ]
 [42.        ]
 [23.        ]
 [29.69911765]
 [15.        ]
 [25.        ]
 [29.69911765]
 [28.        ]
 [22.        ]
 [38.        ]
 [29.69911765]
 [29.69911765]
 [40.        ]
 [29.        ]
 [45.        ]
 [35.        ]
 [29.69911765]
 [30.        ]
 [60.        ]
 [29.69911765]
 [29.69911765]
 [24.        ]
 [25.        ]
 [18.        ]
 [19.        ]
 [22.        ]
 [ 3.        ]
 [29.69911765]
 [22.        ]
 [27.        ]
 [20.        ]
 [19.        ]
 [42.        ]
 [ 1.        ]
 [32.        ]
 [35.        ]
 [29.69911765]
 [18.        ]
 [ 1.        ]
 [36.        ]
 [29.69911765]
 [17.        ]
 [36.        ]
 [21.        ]
 [28.        ]
 [23.        ]
 [24.        ]
 [22.        ]
 [31.        ]
 [46.        ]
 [23.        ]
 [28.        ]
 [39.        ]
 [26.        ]
 [21.        ]
 [28.        ]
 [20.        ]
 [34.        ]
 [51.        ]
 [ 3.        ]
 [21.        ]
 [29.69911765]
 [29.69911765]
 [29.69911765]
 [33.        ]
 [29.69911765]
 [44.        ]
 [29.69911765]
 [34.        ]
 [18.        ]
 [30.        ]
 [10.        ]
 [29.69911765]
 [21.        ]
 [29.        ]
 [28.        ]
 [18.        ]
 [29.69911765]
 [28.        ]
 [19.        ]
 [29.69911765]
 [32.        ]
 [28.        ]
 [29.69911765]
 [42.        ]
 [17.        ]
 [50.        ]
 [14.        ]
 [21.        ]
 [24.        ]
 [64.        ]
 [31.        ]
 [45.        ]
 [20.        ]
 [25.        ]
 [28.        ]
 [29.69911765]
 [ 4.        ]
 [13.        ]
 [34.        ]
 [ 5.        ]
 [52.        ]
 [36.        ]
 [29.69911765]
 [30.        ]
 [49.        ]
 [29.69911765]
 [29.        ]
 [65.        ]
 [29.69911765]
 [50.        ]
 [29.69911765]
 [48.        ]
 [34.        ]
 [47.        ]
 [48.        ]
 [29.69911765]
 [38.        ]
 [29.69911765]
 [56.        ]
 [29.69911765]
 [ 0.75      ]
 [29.69911765]
 [38.        ]
 [33.        ]
 [23.        ]
 [22.        ]
 [29.69911765]
 [34.        ]
 [29.        ]
 [22.        ]
 [ 2.        ]
 [ 9.        ]
 [29.69911765]
 [50.        ]
 [63.        ]
 [25.        ]
 [29.69911765]
 [35.        ]
 [58.        ]
 [30.        ]
 [ 9.        ]
 [29.69911765]
 [21.        ]
 [55.        ]
 [71.        ]
 [21.        ]
 [29.69911765]
 [54.        ]
 [29.69911765]
 [25.        ]
 [24.        ]
 [17.        ]
 [21.        ]
 [29.69911765]
 [37.        ]
 [16.        ]
 [18.        ]
 [33.        ]
 [29.69911765]
 [28.        ]
 [26.        ]
 [29.        ]
 [29.69911765]
 [36.        ]
 [54.        ]
 [24.        ]
 [47.        ]
 [34.        ]
 [29.69911765]
 [36.        ]
 [32.        ]
 [30.        ]
 [22.        ]
 [29.69911765]
 [44.        ]
 [29.69911765]
 [40.5       ]
 [50.        ]
 [29.69911765]
 [39.        ]
 [23.        ]
 [ 2.        ]
 [29.69911765]
 [17.        ]
 [29.69911765]
 [30.        ]
 [ 7.        ]
 [45.        ]
 [30.        ]
 [29.69911765]
 [22.        ]
 [36.        ]
 [ 9.        ]
 [11.        ]
 [32.        ]
 [50.        ]
 [64.        ]
 [19.        ]
 [29.69911765]
 [33.        ]
 [ 8.        ]
 [17.        ]
 [27.        ]
 [29.69911765]
 [22.        ]
 [22.        ]
 [62.        ]
 [48.        ]
 [29.69911765]
 [39.        ]
 [36.        ]
 [29.69911765]
 [40.        ]
 [28.        ]
 [29.69911765]
 [29.69911765]
 [24.        ]
 [19.        ]
 [29.        ]
 [29.69911765]
 [32.        ]
 [62.        ]
 [53.        ]
 [36.        ]
 [29.69911765]
 [16.        ]
 [19.        ]
 [34.        ]
 [39.        ]
 [29.69911765]
 [32.        ]
 [25.        ]
 [39.        ]
 [54.        ]
 [36.        ]
 [29.69911765]
 [18.        ]
 [47.        ]
 [60.        ]
 [22.        ]
 [29.69911765]
 [35.        ]
 [52.        ]
 [47.        ]
 [29.69911765]
 [37.        ]
 [36.        ]
 [29.69911765]
 [49.        ]
 [29.69911765]
 [49.        ]
 [24.        ]
 [29.69911765]
 [29.69911765]
 [44.        ]
 [35.        ]
 [36.        ]
 [30.        ]
 [27.        ]
 [22.        ]
 [40.        ]
 [39.        ]
 [29.69911765]
 [29.69911765]
 [29.69911765]
 [35.        ]
 [24.        ]
 [34.        ]
 [26.        ]
 [ 4.        ]
 [26.        ]
 [27.        ]
 [42.        ]
 [20.        ]
 [21.        ]
 [21.        ]
 [61.        ]
 [57.        ]
 [21.        ]
 [26.        ]
 [29.69911765]
 [80.        ]
 [51.        ]
 [32.        ]
 [29.69911765]
 [ 9.        ]
 [28.        ]
 [32.        ]
 [31.        ]
 [41.        ]
 [29.69911765]
 [20.        ]
 [24.        ]
 [ 2.        ]
 [29.69911765]
 [ 0.75      ]
 [48.        ]
 [19.        ]
 [56.        ]
 [29.69911765]
 [23.        ]
 [29.69911765]
 [18.        ]
 [21.        ]
 [29.69911765]
 [18.        ]
 [24.        ]
 [29.69911765]
 [32.        ]
 [23.        ]
 [58.        ]
 [50.        ]
 [40.        ]
 [47.        ]
 [36.        ]
 [20.        ]
 [32.        ]
 [25.        ]
 [29.69911765]
 [43.        ]
 [29.69911765]
 [40.        ]
 [31.        ]
 [70.        ]
 [31.        ]
 [29.69911765]
 [18.        ]
 [24.5       ]
 [18.        ]
 [43.        ]
 [36.        ]
 [29.69911765]
 [27.        ]
 [20.        ]
 [14.        ]
 [60.        ]
 [25.        ]
 [14.        ]
 [19.        ]
 [18.        ]
 [15.        ]
 [31.        ]
 [ 4.        ]
 [29.69911765]
 [25.        ]
 [60.        ]
 [52.        ]
 [44.        ]
 [29.69911765]
 [49.        ]
 [42.        ]
 [18.        ]
 [35.        ]
 [18.        ]
 [25.        ]
 [26.        ]
 [39.        ]
 [45.        ]
 [42.        ]
 [22.        ]
 [29.69911765]
 [24.        ]
 [29.69911765]
 [48.        ]
 [29.        ]
 [52.        ]
 [19.        ]
 [38.        ]
 [27.        ]
 [29.69911765]
 [33.        ]
 [ 6.        ]
 [17.        ]
 [34.        ]
 [50.        ]
 [27.        ]
 [20.        ]
 [30.        ]
 [29.69911765]
 [25.        ]
 [25.        ]
 [29.        ]
 [11.        ]
 [29.69911765]
 [23.        ]
 [23.        ]
 [28.5       ]
 [48.        ]
 [35.        ]
 [29.69911765]
 [29.69911765]
 [29.69911765]
 [36.        ]
 [21.        ]
 [24.        ]
 [31.        ]
 [70.        ]
 [16.        ]
 [30.        ]
 [19.        ]
 [31.        ]
 [ 4.        ]
 [ 6.        ]
 [33.        ]
 [23.        ]
 [48.        ]
 [ 0.67      ]
 [28.        ]
 [18.        ]
 [34.        ]
 [33.        ]
 [29.69911765]
 [41.        ]
 [20.        ]
 [36.        ]
 [16.        ]
 [51.        ]
 [29.69911765]
 [30.5       ]
 [29.69911765]
 [32.        ]
 [24.        ]
 [48.        ]
 [57.        ]
 [29.69911765]
 [54.        ]
 [18.        ]
 [29.69911765]
 [ 5.        ]
 [29.69911765]
 [43.        ]
 [13.        ]
 [17.        ]
 [29.        ]
 [29.69911765]
 [25.        ]
 [25.        ]
 [18.        ]
 [ 8.        ]
 [ 1.        ]
 [46.        ]
 [29.69911765]
 [16.        ]
 [29.69911765]
 [29.69911765]
 [25.        ]
 [39.        ]
 [49.        ]
 [31.        ]
 [30.        ]
 [30.        ]
 [34.        ]
 [31.        ]
 [11.        ]
 [ 0.42      ]
 [27.        ]
 [31.        ]
 [39.        ]
 [18.        ]
 [39.        ]
 [33.        ]
 [26.        ]
 [39.        ]
 [35.        ]
 [ 6.        ]
 [30.5       ]
 [29.69911765]
 [23.        ]
 [31.        ]
 [43.        ]
 [10.        ]
 [52.        ]
 [27.        ]
 [38.        ]
 [27.        ]
 [ 2.        ]
 [29.69911765]
 [29.69911765]
 [ 1.        ]
 [29.69911765]
 [62.        ]
 [15.        ]
 [ 0.83      ]
 [29.69911765]
 [23.        ]
 [18.        ]
 [39.        ]
 [21.        ]
 [29.69911765]
 [32.        ]
 [29.69911765]
 [20.        ]
 [16.        ]
 [30.        ]
 [34.5       ]
 [17.        ]
 [42.        ]
 [29.69911765]
 [35.        ]
 [28.        ]
 [29.69911765]
 [ 4.        ]
 [74.        ]
 [ 9.        ]
 [16.        ]
 [44.        ]
 [18.        ]
 [45.        ]
 [51.        ]
 [24.        ]
 [29.69911765]
 [41.        ]
 [21.        ]
 [48.        ]
 [29.69911765]
 [24.        ]
 [42.        ]
 [27.        ]
 [31.        ]
 [29.69911765]
 [ 4.        ]
 [26.        ]
 [47.        ]
 [33.        ]
 [47.        ]
 [28.        ]
 [15.        ]
 [20.        ]
 [19.        ]
 [29.69911765]
 [56.        ]
 [25.        ]
 [33.        ]
 [22.        ]
 [28.        ]
 [25.        ]
 [39.        ]
 [27.        ]
 [19.        ]
 [29.69911765]
 [26.        ]
 [32.        ]]